EdisonGame/Models/GameModel/GameContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EdisonGame.Models.GameModel
{
    public class GameContext
    {
        public static GameGlobal TheGame { get; set; }

        static GameContext()
        {
            TheGame  = new GameGlobal();
        }
    }
}

EdisonGame/Models/GameModel/GameGlobal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EdisonGame.Models.Identity;

namespace EdisonGame.Models.GameModel
{
    public class GameGlobal
    {
        public GameGlobal()
        {
            this.Lobbies = new List<Lobby>();
        }

        public IEnumerable<GameUser> AllUsers { get; set; }
        public IEnumerable<GameUser> OnlineUsers { get; set; }
        public List<Lobby> Lobbies { get; set; }
    }
}

EdisonGame/Models/GameModel/Lobby.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using EdisonGame.Models.Identity;

namespace EdisonGame.Models.GameModel
{
    public class Lobby
    {
        public Lobby()
        {
            this.Gamers = new List<GameUser>();
            LobbyName = "";
            LobbyCapacity = 6;
        }

        [Required]
        public String LobbyName { get; set; }
        [Required]
        public int LobbyCapacity { get; set; }
        [Required]
        public Boolean InGameAutomaticaly { get; set; }
        public List<GameUser> Gamers { get; set; }
        public GameUser Creator;

        public void Join(GameUser gamer)
        {
            if(!Gamers.Contains(gamer))
                Gamers.Add(gamer);
        }

        public void Exit(GameUser gamer)
        {
            Gamers.Remove(gamer);
        }
    }
}

EdisonGame/Models/GameModel/OnlineUsersStorage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EdisonGame.Models.Identity;

namespace EdisonGame.Models.GameModel
{
    public class OnlineUsersStorage
    {
        private static List<GameUser> _onlineUsers = new List<GameUser>();

        public static void UserLogIn(GameUser user)
        {
            if (!_onlineUsers.Contains(user))
                _onlineUsers.Add(user);
        }

        public static void UserLogOf(GameUser user)
        {
            _onlineUsers.Remove(user);
        }

        public static IEnumerable<GameUser> OnlineUsers
        {
            get { return _onlineUsers; }
        }
    }
}

EdisonGame/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EdisonGame.Models.Identity;
using EdisonGame.Models.GameModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace EdisonGame.Controllers
{
    [Authorize]
    public class AuthorizeController : Controller
    {
        private GameUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<GameUserManager>(); }
        }
        //
        // GET: /Home/
        [AllowAnonymous]
        public ActionResult LogIn(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();         
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginModel details, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                GameUser user = await UserManager.FindAsync(details.Name, details.Password);
                if (user == null)
                {
                    ModelState.AddModelError("", "Invalid name or password.");
                }
                else
                {
                    ClaimsIdentity ident =
                        await UserManager.CreateIdentityAsync(user, 
                        DefaultAuthenticationTypes.ApplicationCookie);
                    AuthManager.SignOut();
                    AuthManager.SignIn(new AuthenticationProperties()
                    { IsPersistent = false }, ident);
                    OnlineUsersStorage.UserLogIn(user);
                    return Redirect("/");
                }
            }

            ViewBag.returnUrl = returnUrl;
            return View(details);
        }

        private IAuthenticationManager AuthManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }


        [AllowAnonymous]
        public ActionResult SignIn()
        {
            return View();
        }

        /// <summary>
        /// Создает пользователя с заданными характеристиками
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> SignIn(UserCreateModel model)
        {
            if (ModelState.IsValid)
            {
                GameUser user = new GameUser() { UserName = model.Login, PublicName = model.PublicName };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    foreach (string error in result.Errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
                return View(model);
            }
            else
            {
                return RedirectToAction("SignIn");
            }
        }

        public ActionResult LogOut()
        {
            GameUser user = UserManager.FindByName(HttpContext.User.Identity.Name);
            OnlineUsersStorage.UserLogOf(user);
            AuthManager.SignOut();            
            return RedirectToAction("LogIn");
        }
	}
}

EdisonGame/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EdisonGame.Hubs;
using EdisonGame.Models.GameModel;
using EdisonGame.Models.Identity;
using EdisonGame.Models.GameModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.SignalR;

namespace EdisonGame.Controllers
{
    [System.Web.Mvc.Authorize]
    public class GameController : Controller
    {
        [HttpPost]
        public ActionResult CreateNewLobby(Lobby newLobby)
        {
            if (ModelState.IsValid)
            {
                newLobby.Creator = CurrentUser;
                if(newLobby.InGameAutomaticaly)
                    newLobby.Join(CurrentUser);

                GameContext.TheGame.Lobbies.Add(newLobby);

                var hubContext = GlobalHost.ConnectionManager.GetHubContext<GameHub>();
                hubContext.Clients.All.interLobbyClient(newLobby.Creator.PublicName, newLobby.LobbyName);

                return RedirectToAction("Index");
            }

            return View("CreateNewLobby");
        }

        public ActionResult CreateNewLobby()
        {
            Lobby lobby = new Lobby();
            return View(lobby);
        }

        public ActionResult Index()
        {
            GameGlobal game = GameContext.TheGame;
            game.AllUsers = HttpContext.GetOwinContext().GetUserManager<GameUserManager>().Users;
            game.OnlineUsers = OnlineUsersStorage.OnlineUsers;

            return View(game);
        }

        private GameUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<GameUserManager>(); }
        }

        private GameUser CurrentUser
        {
            get { return UserManager.FindByName(HttpContext.User.Identity.Name); }
        }
    }
}

EdisonGame/Views/Authorize/Login.cshtml
@model EdisonGame.Models.Identity.LoginModel
@{
    ViewBag.Title = "Игра";
    Layout = "~/Views/_MainLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="spanny"></div>

        @Html.ValidationSummary()
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken();
            <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl"/>
            <div class="input-group input-group-lg">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                </span>
                @Html.TextBoxFor(m=>m.Name, new { @class="form-control", @placeholder="Введите свой логин"})
            </div>
            <br />
            <div class="input-group input-group-lg">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-asterisk"></span>
                </span>
                @Html.TextBoxFor(m => m.Password, new { @class = "form-control", @placeholder = "Введите пароль" })
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Log In</button>
            @Html.ActionLink("Sign In", "SignIn", null, new { @class = "btn btn-default" })
        }

    </div>
</div>

EdisonGame/Views/Authorize/SignIn.cshtml
@model EdisonGame.Models.Identity.UserCreateModel
@{
    ViewBag.Title = "Sign In";
    Layout = "~/Views/_MainLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="spanny"></div>
        @Html.ValidationSummary(false)        
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>User Public Name</label>
                @Html.TextBoxFor(m => m.PublicName, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Login</label>
                @Html.TextBoxFor(m => m.Login, new {@class = "form-control"})
            </div>
            <div class="form-group">
                <label>Password</label>
                @Html.TextBoxFor(m => m.Password, new {@class = "form-control"})
            </div>
            <button type="submit" class="btn btn-info">Create New User</button>
            @Html.ActionLink("Cancel", "Login", null, new { @class = "btn btn-default" })
        }
    </div>
</div>

EdisonGame/Views/Game/CreateNewLobby.cshtml
@using EdisonGame.Models.GameModel
@{
    ViewBag.Title = "CreateNewLobby";
    Layout = "~/Views/_MainLayout.cshtml";
}
@model Lobby

<div class="row">
    <div class="col-lg-12">
        <div class="spanny"></div>
        @Html.ValidationSummary(false)
        
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>Lobby Name</label>
                @Html.TextBoxFor(m => m.LobbyName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Lobby Capacity</label>
                @Html.DropDownListFor(m=>m.LobbyCapacity, new SelectList(
                    new List<object>() { new { value = 4, text = "4"}, 
                        new { value = 6, text = "6"} }, "value", "text"),
                    new { @class = "form-control"})                
            </div>

            <div class="checkbox">
                <label>@Html.CheckBoxFor(m => m.InGameAutomaticaly)I join immediately</label>
            </div>

            <br/>
           
            <button type="submit" class="btn btn-info">Create New Lobby</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
        }
    </div>
</div>

EdisonGame/Views/Game/Index.cshtml
@using EdisonGame.Models.GameModel
@using EdisonGame.Models.Identity
@model GameGlobal
@{
    ViewBag.Title = "Game!";
    Layout = "~/Views/_MainLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 text-right">
        @Html.ActionLink("Exit", "LogOut", "Authorize", null, new {@class = "btn btn-primary"})
    </div>
</div>
<div class="row">
    <div class="btn-group">
        @Html.ActionLink("Create Lobby", "CreateNewLobby", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Delete Lobby", "CreateNewLobby", null, new { @class = "btn btn-default" })
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Lobies 4 (@Model.Lobbies.Where(p => p.LobbyCapacity == 4).ToList().Count))</h2>

        @foreach (Lobby lobby in Model.Lobbies.Where(p => p.LobbyCapacity == 4))
        {
            <div class="thumbnail">
                <h4>@lobby.LobbyName</h4>
                <p>Количество игроков: @lobby.LobbyCapacity</p>
                <p>Приcоединились: @lobby.Gamers.Count</p>
                <div class="btn-group-sm">
                    <button class="btn btn-default">Join!</button>
                    <button class="btn btn-default">Leave</button>
                </div>
            </div>
        }
    </div>

    <div class="col-md-6">
        <h2>Lobies 6 (@Model.Lobbies.Where(p => p.LobbyCapacity == 6).ToList().Count))</h2>

        @foreach (Lobby lobby in Model.Lobbies.Where(p => p.LobbyCapacity == 6))
        {
            <div class="thumbnail">
                <h4>@lobby.LobbyName</h4>
                <p>Количество игроков: @lobby.LobbyCapacity</p>
                <p>Приcоединились: @lobby.Gamers.Count</p>
                <div class="btn-group-sm">
                    <button class="btn btn-default">Join!</button>
                    <button class="btn btn-default">Leave</button>
                </div>
            </div>
        }
    </div>

    <div class="col-md-6">
        <h2>Online Users</h2>

        @foreach (GameUser user in Model.OnlineUsers)
        {
            <div class="alert alert-success">
                <p>@user.PublicName</p>
                <p>@user.UserName</p>
                <p>@user.Id</p>
            </div>
        }
    </div>

    <div class="col-md-6">
        <h2>All Users</h2>

        @foreach (GameUser user in Model.AllUsers)
        {
            <div class="alert alert-info">
                <p>@user.PublicName</p>
                <p>@user.UserName</p>
                <p>@user.Id</p>
            </div>
        }
    </div>

</div>

EdisonGame/Views/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet"/>
    <link href="~/Content/custom.css" rel="stylesheet" />
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Моя игра</h1>
        </div>
    </div>
    @RenderBody()
</div>

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="~/signalr/hubs" type="text/javascript"></script>
<script src="~/Scripts/custom.js" type="text/javascript"></script>
</body>
</html>